// <auto-generated />
using System;
using Emp.DLL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emp.DLL.Migrations
{
    [DbContext(typeof(EmpSystemDbContext))]
    partial class EmpSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emp.DLL.Enities.Deparment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Deparments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "HR"
                        },
                        new
                        {
                            ID = 2,
                            Name = "IT"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("Emp.DLL.Enities.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentId = 1,
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe",
                            Salary = 50000m
                        },
                        new
                        {
                            ID = 2,
                            DepartmentId = 2,
                            HireDate = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith",
                            Salary = 60000m
                        },
                        new
                        {
                            ID = 3,
                            DepartmentId = 2,
                            HireDate = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson",
                            Salary = 55000m
                        },
                        new
                        {
                            ID = 4,
                            DepartmentId = 3,
                            HireDate = new DateTime(2018, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mark Thompson",
                            Salary = 70000m
                        },
                        new
                        {
                            ID = 5,
                            DepartmentId = 3,
                            HireDate = new DateTime(2022, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emily Brown",
                            Salary = 48000m
                        },
                        new
                        {
                            ID = 6,
                            DepartmentId = 4,
                            HireDate = new DateTime(2020, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "David Wilson",
                            Salary = 62000m
                        });
                });

            modelBuilder.Entity("Emp.DLL.Enities.Employee", b =>
                {
                    b.HasOne("Emp.DLL.Enities.Deparment", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Emp.DLL.Enities.Deparment", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
